const RUNTIME_HELPERS = [
  'function bridgeLookupSequence(sequenceId) {',
  '  for (var i = 0; i < app.project.sequences.numSequences; i++) {',
  '    if (app.project.sequences[i].sequenceID === sequenceId) return app.project.sequences[i];',
  '  }',
  '  return null;',
  '}',
  'function bridgeLookupClip(nodeId) {',
  '  function searchSequence(sequence) {',
  '    if (!sequence) return null;',
  "    for (var videoTrackIndex = 0; videoTrackIndex < sequence.videoTracks.numTracks; videoTrackIndex++) {",
  '      var videoTrack = sequence.videoTracks[videoTrackIndex];',
  '      for (var videoClipIndex = 0; videoClipIndex < videoTrack.clips.numItems; videoClipIndex++) {',
  '        if (videoTrack.clips[videoClipIndex].nodeId === nodeId) {',
  "          return { clip: videoTrack.clips[videoClipIndex], sequence: sequence, track: videoTrack, trackIndex: videoTrackIndex, clipIndex: videoClipIndex, trackType: 'video' };",
  '        }',
  '      }',
  '    }',
  "    for (var audioTrackIndex = 0; audioTrackIndex < sequence.audioTracks.numTracks; audioTrackIndex++) {",
  '      var audioTrack = sequence.audioTracks[audioTrackIndex];',
  '      for (var audioClipIndex = 0; audioClipIndex < audioTrack.clips.numItems; audioClipIndex++) {',
  '        if (audioTrack.clips[audioClipIndex].nodeId === nodeId) {',
  "          return { clip: audioTrack.clips[audioClipIndex], sequence: sequence, track: audioTrack, trackIndex: audioTrackIndex, clipIndex: audioClipIndex, trackType: 'audio' };",
  '        }',
  '      }',
  '    }',
  '    return null;',
  '  }',
  '  var activeSequence = app.project.activeSequence;',
  '  var activeMatch = searchSequence(activeSequence);',
  '  if (activeMatch) return activeMatch;',
  '  for (var sequenceIndex = 0; sequenceIndex < app.project.sequences.numSequences; sequenceIndex++) {',
  '    var sequence = app.project.sequences[sequenceIndex];',
  '    if (!sequence || sequence === activeSequence) continue;',
  '    var match = searchSequence(sequence);',
  '    if (match) return match;',
  '  }',
  '  return null;',
  '}',
  'function bridgeLookupProjectItem(nodeId) {',
  '  function walk(currentItem) {',
  '    if (currentItem.nodeId === nodeId) return currentItem;',
  '    if (currentItem.children) {',
  '      for (var i = 0; i < currentItem.children.numItems; i++) {',
  '        var foundItem = walk(currentItem.children[i]);',
  '        if (foundItem) return foundItem;',
  '      }',
  '    }',
  '    return null;',
  '  }',
  '  return walk(app.project.rootItem);',
  '}',
  'function bridgeLookupChild(parentItem, childName) {',
  '  if (!parentItem || !parentItem.children) return null;',
  '  for (var i = 0; i < parentItem.children.numItems; i++) {',
  '    var childItem = parentItem.children[i];',
  '    if (childItem && childItem.name === childName) return childItem;',
  '  }',
  '  return null;',
  '}',
  'function bridgeTicksToSeconds(ticks) {',
  '  return parseInt(ticks, 10) / 254016000000;',
  '}',
  'function bridgeSecondsToTicks(seconds) {',
  '  return String(Math.round(seconds * 254016000000));',
  '}',
];

export const EXTENDSCRIPT_RUNTIME_SOURCE = `${RUNTIME_HELPERS.join('\n')}\n`;

export function wrapBridgeScript(script: string): string {
  return `${EXTENDSCRIPT_RUNTIME_SOURCE}(function(){\n${script}\n})();`;
}
