import { z } from 'zod';

const MOTION_STYLE_OPTIONS = ['push_in', 'pull_out', 'alternate', 'none'] as const;
const MATCH_STRATEGY_OPTIONS = ['keyword', 'blueprint'] as const;

type ToolCatalogEntry = {
  name: string;
  description: string;
  inputSchema: z.ZodSchema<any>;
};

export function createHighLevelToolCatalogSnapshot(options: {
  referenceOnlyMediaPolicy: string;
  animationPresetNames: readonly [string, ...string[]];
}): ToolCatalogEntry[] {
  const { referenceOnlyMediaPolicy, animationPresetNames } = options;

  return [
    {
      name: 'list_project_items',
      description: 'Lists all media items, bins, and assets in the current Premiere Pro project. Use this to discover available media before performing operations.',
      inputSchema: z.object({
        includeBins: z.boolean().optional().describe('Whether to include bin information in the results'),
        includeMetadata: z.boolean().optional().describe('Whether to include detailed metadata for each item'),
      }),
    },
    {
      name: 'list_sequences',
      description: 'Lists all sequences in the current Premiere Pro project with their IDs, names, and basic properties.',
      inputSchema: z.object({}),
    },
    {
      name: 'list_sequence_tracks',
      description: 'Lists all video and audio tracks in a specific sequence with their properties and clips.',
      inputSchema: z.object({
        sequenceId: z.string().describe('The ID of the sequence to list tracks for'),
      }),
    },
    {
      name: 'get_project_info',
      description: 'Gets comprehensive information about the current project including name, path, settings, and status.',
      inputSchema: z.object({}),
    },
    {
      name: 'build_motion_graphics_demo',
      description: 'Generates clean demo stills, creates a sequence, lays the shots out on the timeline, optionally adds transitions, and applies subtle scale animation for a polished minimalist ad-style demo.',
      inputSchema: z.object({
        sequenceName: z.string().optional().describe('Optional sequence name. Defaults to "Apple Like Motion Demo".'),
        transitionName: z.string().optional().describe('Optional transition to apply between adjacent demo clips. If omitted, the demo workflow will not add automatic clip transitions.'),
        transitionDuration: z.number().optional().describe('Transition duration in seconds when transitionName is explicitly provided. Defaults to 0.75 in that case.'),
        naturalLanguagePrompt: z.string().optional().describe('Optional natural-language request used to derive demo transition defaults when explicit transition args are omitted.'),
        referenceBlueprintPath: z.string().optional().describe('Optional JSON blueprint path used to derive demo transition defaults. Takes priority over naturalLanguagePrompt.'),
      }),
    },
    {
      name: 'plan_edit_assembly',
      description: 'Builds a deterministic assembly candidate from a DOCX guide and a scanned media manifest so AI can inspect a reference-only playback order before high-level Premiere execution.',
      inputSchema: z.object({
        docxPath: z.string().describe('Absolute path to the DOCX guide that defines the intended edit.'),
        mediaManifestPath: z.string().describe('Absolute path to the JSON manifest generated by scan:media.'),
        sequenceName: z.string().optional().describe('Optional override for the planned sequence name.'),
        maxAssets: z.number().optional().describe('Optional cap on the number of selected visual assets.'),
        transitionName: z.string().optional().describe('Optional override for the planned clip transition name.'),
        transitionPolicy: z.string().optional().describe('Optional override for the planned transition policy label.'),
        clipDuration: z.number().optional().describe('Optional override for the planned default clip duration in seconds.'),
        motionStyle: z.enum(MOTION_STYLE_OPTIONS).optional().describe('Optional override for the planned motion style.'),
        mediaPolicy: z.string().optional().describe('Optional candidate media policy so the plan can surface mismatches.'),
        referenceBlueprintPath: z.string().optional().describe('Optional JSON blueprint path used to switch asset selection into blueprint matching mode.'),
        matchStrategy: z.enum(MATCH_STRATEGY_OPTIONS).optional().describe('Optional asset matching strategy. Defaults to keyword unless a reference blueprint is provided.'),
        minMatchScore: z.number().optional().describe('Optional minimum blueprint match score. Defaults to 0.4.'),
      }),
    },
    {
      name: 'assemble_product_spot',
      description: 'Builds a production-oriented promo timeline from real media assets by importing them, creating a sequence, laying them out in order, adding transitions, and applying simple motion treatment. This is useful for rough cuts, product promos, and ad assembly from existing assets.',
      inputSchema: z.object({
        sequenceName: z.string().describe('Name for the new sequence'),
        assetPaths: z.array(z.string()).min(1).optional().describe('Optional absolute paths to video or image assets in playback order. Required unless autoPlanFromManifest is enabled.'),
        docxPath: z.string().optional().describe('Optional DOCX guide path for pre-assembly review. Required when reviewBeforeAssemble is true.'),
        mediaManifestPath: z.string().optional().describe('Optional scanned media manifest JSON path for pre-assembly review. Required when reviewBeforeAssemble is true.'),
        autoPlanFromManifest: z.boolean().optional().describe('Whether to derive assetPaths and safe defaults from docxPath + mediaManifestPath when assetPaths are omitted.'),
        maxPlannedAssets: z.number().optional().describe('Optional cap for auto-planned visual assets when autoPlanFromManifest is enabled.'),
        referenceBlueprintPath: z.string().optional().describe('Optional JSON blueprint path used to match scanned assets against a reference edit.'),
        editingBlueprintPath: z.string().optional().describe('Optional JSON editing blueprint path produced by external research tooling. Used to derive clip timing and transition defaults when referenceBlueprintPath is not provided.'),
        naturalLanguagePrompt: z.string().optional().describe('Optional natural-language request used to derive clip timing and transition defaults before assembly. Ignored when referenceBlueprintPath or editingBlueprintPath is provided.'),
        applyGuideEffects: z.boolean().optional().describe('Whether to apply guide-derived global clip effects after auto planning. Defaults to false.'),
        reviewBeforeAssemble: z.boolean().optional().describe('Whether to run reasonability review before creating the sequence.'),
        allowReviewWarnings: z.boolean().optional().describe('Whether needs-review results may proceed without manual confirmation. Defaults to false.'),
        mediaPolicy: z.enum([referenceOnlyMediaPolicy]).optional().describe('Source media handling policy. Defaults to reference-only and must not copy source files.'),
        clipDuration: z.number().optional().describe('Default placement duration in seconds for stills and rough spacing for assets. Defaults to 4.0'),
        videoTrackIndex: z.number().optional().describe('Target video track index. Defaults to 0'),
        transitionName: z.string().optional().describe('Optional transition to apply between adjacent clips. If omitted, the workflow will not add automatic clip transitions.'),
        transitionPolicy: z.string().optional().describe('Optional transition policy label used by the pre-assembly review.'),
        transitionDuration: z.number().optional().describe('Transition duration in seconds when transitionName is explicitly provided. Defaults to 0.5 in that case.'),
        motionStyle: z.enum(MOTION_STYLE_OPTIONS).optional().describe('Simple scale animation style. Defaults to "none" unless an explicit move is requested.'),
      }),
    },
    {
      name: 'assemble_product_spot_closed_loop',
      description: 'One-click viral-style assembly from an external research blueprint. This loads the EditingBlueprint, reviews it, runs assemble_product_spot, compares the finished timeline to the blueprint, and runs the independent critic before reporting delivery readiness.',
      inputSchema: z.object({
        goal: z.string().describe('Editing goal used for blueprint review, critic review, and final delivery checks.'),
        sequenceName: z.string().describe('Name for the new sequence'),
        researchTaskDir: z.string().optional().describe('Optional research task directory that contains blueprint.json from video-research-mcp. Used when editingBlueprintPath is omitted.'),
        editingBlueprintPath: z.string().optional().describe('Optional absolute path to an external EditingBlueprint JSON file.'),
        assetPaths: z.array(z.string()).min(1).optional().describe('Optional absolute paths to video or image assets in playback order. Required unless autoPlanFromManifest is enabled.'),
        docxPath: z.string().optional().describe('Optional DOCX guide path for pre-assembly review. Required when reviewBeforeAssemble is true.'),
        mediaManifestPath: z.string().optional().describe('Optional scanned media manifest JSON path for pre-assembly review. Required when reviewBeforeAssemble is true.'),
        autoPlanFromManifest: z.boolean().optional().describe('Whether to derive assetPaths and safe defaults from docxPath + mediaManifestPath when assetPaths are omitted.'),
        maxPlannedAssets: z.number().optional().describe('Optional cap for auto-planned visual assets when autoPlanFromManifest is enabled.'),
        applyGuideEffects: z.boolean().optional().describe('Whether to apply guide-derived global clip effects after auto planning. Defaults to false.'),
        reviewBeforeAssemble: z.boolean().optional().describe('Whether to run reasonability review before creating the sequence. Defaults to true in this closed-loop workflow.'),
        allowReviewWarnings: z.boolean().optional().describe('Whether needs-review results may proceed without manual confirmation. Defaults to false.'),
        mediaPolicy: z.enum([referenceOnlyMediaPolicy]).optional().describe('Source media handling policy. Defaults to reference-only and must not copy source files.'),
        clipDuration: z.number().optional().describe('Default placement duration in seconds for stills and rough spacing for assets.'),
        videoTrackIndex: z.number().optional().describe('Target video track index. Defaults to 0.'),
        transitionName: z.string().optional().describe('Optional transition to apply between adjacent clips. If omitted, the workflow may derive a transition from the blueprint.'),
        transitionPolicy: z.string().optional().describe('Optional transition policy label used by the pre-assembly review.'),
        transitionDuration: z.number().optional().describe('Transition duration in seconds when transitionName is explicitly provided. Defaults to 0.5 in that case.'),
        motionStyle: z.enum(MOTION_STYLE_OPTIONS).optional().describe('Simple scale animation style. Defaults to the blueprint-derived motion style when omitted.'),
        subtitleSourcePath: z.string().optional().describe('Optional audio or video path used to generate subtitle captions when the blueprint expects text overlays.'),
        subtitleLanguage: z.string().optional().describe('Optional language code for subtitle generation, such as zh or en.'),
        subtitleBackend: z.enum(['auto', 'openai', 'faster-whisper']).optional().describe('Optional subtitle backend override. Defaults to auto.'),
        captionFormat: z.string().optional().describe('Optional Premiere caption format for generated subtitles. Defaults to Subtitle Default.'),
        bgmPath: z.string().optional().describe('Optional BGM or music file path used to analyze beats and create sequence markers when the blueprint expects beat-driven cutting.'),
        beatMarkerPrefix: z.string().optional().describe('Optional sequence marker name prefix for beat markers. Defaults to BEAT.'),
        beatsPerBar: z.number().optional().describe('Optional beats-per-bar hint for strong-beat planning. Defaults to 4.'),
        minimumBlueprintAdherenceScore: z.number().optional().describe('Minimum compare_result_to_blueprint adherence score required for delivery. Defaults to 70.'),
        maxAllowedBlueprintDeviations: z.number().optional().describe('Maximum compare_result_to_blueprint deviation count allowed for delivery. Defaults to 2.'),
      }).refine(
        (value) => Boolean(value.editingBlueprintPath || value.researchTaskDir),
        {
          message: 'editingBlueprintPath or researchTaskDir is required',
          path: ['editingBlueprintPath'],
        },
      ),
    },
    {
      name: 'build_brand_spot_from_mogrt_and_assets',
      description: 'Builds a more polished ad assembly from real media assets, then optionally layers in a supplied MOGRT title card and applies a light finishing pass. This is the practical workflow for reusable branded promos when you already have source media and motion templates.',
      inputSchema: z.object({
        sequenceName: z.string().describe('Name for the new sequence'),
        assetPaths: z.array(z.string()).min(1).optional().describe('Optional absolute paths to source assets in edit order. Required unless autoPlanFromManifest is enabled.'),
        docxPath: z.string().optional().describe('Optional DOCX guide path for pre-assembly review. Required when reviewBeforeAssemble is true.'),
        mediaManifestPath: z.string().optional().describe('Optional scanned media manifest JSON path for pre-assembly review. Required when reviewBeforeAssemble is true.'),
        autoPlanFromManifest: z.boolean().optional().describe('Whether to derive assetPaths and safe defaults from docxPath + mediaManifestPath when assetPaths are omitted.'),
        maxPlannedAssets: z.number().optional().describe('Optional cap for auto-planned visual assets when autoPlanFromManifest is enabled.'),
        referenceBlueprintPath: z.string().optional().describe('Optional JSON blueprint path used to match scanned assets against a reference edit.'),
        editingBlueprintPath: z.string().optional().describe('Optional JSON editing blueprint path produced by external research tooling. Used to derive clip timing and transition defaults when referenceBlueprintPath is not provided.'),
        naturalLanguagePrompt: z.string().optional().describe('Optional natural-language request used to derive clip timing and transition defaults before assembly. Ignored when referenceBlueprintPath or editingBlueprintPath is provided.'),
        applyGuideEffects: z.boolean().optional().describe('Whether to apply guide-derived global clip effects after auto planning. Defaults to false.'),
        reviewBeforeAssemble: z.boolean().optional().describe('Whether to run reasonability review before creating the sequence.'),
        allowReviewWarnings: z.boolean().optional().describe('Whether needs-review results may proceed without manual confirmation. Defaults to false.'),
        mediaPolicy: z.enum([referenceOnlyMediaPolicy]).optional().describe('Source media handling policy. Defaults to reference-only and must not copy source files.'),
        mogrtPath: z.string().optional().describe('Optional absolute path to a .mogrt title or branding template'),
        clipDuration: z.number().optional().describe('Default spacing in seconds for asset placement. Defaults to 4.0'),
        videoTrackIndex: z.number().optional().describe('Base video track for the main assets. Defaults to 0'),
        titleTrackIndex: z.number().optional().describe('Video track for the optional MOGRT overlay. Defaults to 1'),
        titleStartTime: z.number().optional().describe('Timeline start time in seconds for the optional MOGRT. Defaults to 0.4'),
        transitionName: z.string().optional().describe('Optional transition to apply between adjacent clips. If omitted, the workflow will not add automatic clip transitions.'),
        transitionPolicy: z.string().optional().describe('Optional transition policy label used by the pre-assembly review.'),
        transitionDuration: z.number().optional().describe('Transition duration in seconds when transitionName is explicitly provided. Defaults to 0.5 in that case.'),
        motionStyle: z.enum(MOTION_STYLE_OPTIONS).optional().describe('Simple scale animation style. Defaults to "none" unless an explicit move is requested.'),
      }),
    },
    {
      name: 'review_edit_reasonability',
      description: 'Reviews a DOCX guide, a scanned media manifest, and optional candidate edit settings before high-level assembly so obvious plan issues are caught before Premiere execution.',
      inputSchema: z.object({
        docxPath: z.string().describe('Absolute path to the DOCX guide that defines the intended edit.'),
        mediaManifestPath: z.string().describe('Absolute path to the JSON manifest generated by scan:media.'),
        assetPaths: z.array(z.string()).optional().describe('Optional candidate visual asset paths to review in playback order.'),
        transitionName: z.string().optional().describe('Optional candidate clip transition name.'),
        transitionPolicy: z.string().optional().describe('Optional candidate transition policy label.'),
        clipDuration: z.number().optional().describe('Optional candidate default clip duration in seconds.'),
        motionStyle: z.enum(MOTION_STYLE_OPTIONS).optional().describe('Optional candidate motion style for the planned assembly.'),
        mediaPolicy: z.string().optional().describe('Optional candidate media policy so review can flag non-reference-only plans.'),
      }),
    },
    {
      name: 'analyze_reference_video',
      description: 'Analyzes a local reference video and returns a deterministic video blueprint that can guide later replication planning.',
      inputSchema: z.object({
        videoPath: z.string().describe('Absolute path to the local reference video file.'),
      }),
    },
    {
      name: 'plan_replication_from_video',
      description: 'Builds a deterministic replication plan by analyzing a local reference video and matching its shots against a scanned media manifest.',
      inputSchema: z.object({
        videoPath: z.string().describe('Absolute path to the local reference video file.'),
        mediaManifestPath: z.string().describe('Absolute path to the JSON media manifest generated by scan:media.'),
        sequenceName: z.string().optional().describe('Optional label for the replication plan result.'),
      }),
    },
    {
      name: 'compare_to_reference_video',
      description: 'Compares an assembly review payload to a freshly analyzed reference video blueprint and returns a QA report.',
      inputSchema: z.object({
        videoPath: z.string().describe('Absolute path to the local reference video file.'),
        assemblyReviewJson: z.string().describe('Serialized JSON payload describing the realized assembly review or timeline snapshot.'),
      }),
    },
    {
      name: 'parse_edit_request',
      description: 'Parses a natural-language edit request into deterministic intent fields without calling external LLM APIs.',
      inputSchema: z.object({
        prompt: z.string().describe('Natural-language request describing the desired video.'),
        maxDurationSec: z.number().optional().describe('Optional fallback duration when the request does not include a time target.'),
      }),
    },
    {
      name: 'plan_edit_from_request',
      description: 'Builds a deterministic assembly plan from a natural-language request and an optional scanned media manifest.',
      inputSchema: z.object({
        prompt: z.string().describe('Natural-language request describing the desired video.'),
        mediaManifestPath: z.string().optional().describe('Optional JSON media manifest generated by scan:media.'),
        maxDurationSec: z.number().optional().describe('Optional fallback duration when the request does not include a time target.'),
        sequenceName: z.string().optional().describe('Optional override for the planned sequence name.'),
      }),
    },
    {
      name: 'parse_keyframe_request',
      description: 'Parses a natural-language keyframe animation request into structured animation intent for Premiere properties.',
      inputSchema: z.object({
        prompt: z.string().describe('Natural-language request describing the desired keyframe animation.'),
        durationSec: z.number().optional().describe('Optional override for the main animation duration in seconds.'),
      }),
    },
    {
      name: 'plan_keyframe_animation',
      description: 'Builds an explicit Premiere keyframe plan from a natural-language animation request.',
      inputSchema: z.object({
        prompt: z.string().describe('Natural-language request describing the desired keyframe animation.'),
        target: z.string().optional().describe('Optional label for the target clip or layer. Defaults to the selected target.'),
        startTimeSec: z.number().optional().describe('Optional animation start time in seconds. Defaults to 0.'),
        durationSec: z.number().optional().describe('Optional override for the main animation duration in seconds.'),
        sequenceId: z.string().optional().describe('Optional sequence ID used to resolve frame geometry when needed.'),
        frameWidth: z.number().optional().describe('Optional frame width used to resolve position coordinates.'),
        frameHeight: z.number().optional().describe('Optional frame height used to resolve position coordinates.'),
      }),
    },
    {
      name: 'apply_keyframe_animation',
      description: 'Plans and applies a natural-language keyframe animation directly to a clip by writing the required Premiere keyframes.',
      inputSchema: z.object({
        clipId: z.string().describe('The ID of the clip that should receive the keyframes.'),
        prompt: z.string().describe('Natural-language request describing the desired keyframe animation.'),
        target: z.string().optional().describe('Optional label for the target clip or layer in the returned plan.'),
        startTimeSec: z.number().optional().describe('Optional animation start time in seconds. Defaults to 0.'),
        durationSec: z.number().optional().describe('Optional override for the main animation duration in seconds.'),
        sequenceId: z.string().optional().describe('Optional sequence ID used to resolve frame geometry when needed.'),
        frameWidth: z.number().optional().describe('Optional frame width used to resolve position coordinates.'),
        frameHeight: z.number().optional().describe('Optional frame height used to resolve position coordinates.'),
      }),
    },
    {
      name: 'apply_animation_preset',
      description: 'Applies a named keyframe animation preset to a clip. Presets include fade, zoom, slide, bounce, shake, and spin effects. Faster than natural-language animation when you know exactly which effect you want.',
      inputSchema: z.object({
        clipId: z.string().describe('The ID of the clip to animate.'),
        preset: z.enum(animationPresetNames).describe('Animation preset name. Options: fade_in, fade_out, fade_in_out, zoom_in, zoom_out, slide_left, slide_right, slide_top, slide_bottom, bounce_in, shake, spin_in.'),
        startTimeSec: z.number().optional().describe('Animation start time in seconds. Defaults to 0.'),
        durationSec: z.number().optional().describe('Animation duration in seconds. Defaults to 3.'),
        frameWidth: z.number().optional().describe('Frame width in pixels for slide presets. Defaults to 1920.'),
        frameHeight: z.number().optional().describe('Frame height in pixels for slide presets. Defaults to 1080.'),
      }),
    },
  ];
}
